[
  {
    id: 'alert1',
    action: 'BUY',
    alertName: 'Bitcoin Price Alert',
    description: 'Bitcoin price has reached the target.',
    creationTime: 1698547200,
    activationTime: 1698547300,
    activationTimeStr: '2023-10-29T12:00:00Z',
    price: 29000,
    high: 29500,
    low: 28500,
    tvScreensUrls: [
      'https://www.tradingview.com/chart?symbol=BINANCE:BTCUSDT',
      'https://www.tradingview.com/chart?symbol=KRAKEN:BTCUSD',
    ],
    isActive: true,
    symbol: 'BTCUSDT',
    category: 'Cryptocurrency',
    status: 'TRIGGERED',
    tvLink: 'https://www.tradingview.com/chart?symbol=BINANCE:BTCUSDT',
    cgLink: 'https://www.coingecko.com/en/coins/bitcoin',
    exchanges: ['BINANCE', 'KRAKEN'],
    imageUrl: 'assets/icons/bitcoin.svg',
  },
  {
    id: 'alert2',
    action: 'SELL',
    alertName: 'Ethereum Price Alert',
    description: 'Ethereum price has dropped below the threshold.',
    creationTime: 1698547250,
    activationTime: 1698547350,
    activationTimeStr: '2023-10-29T12:05:00Z',
    price: 1800,
    high: 1850,
    low: 1750,
    tvScreensUrls: ['https://www.tradingview.com/chart?symbol=BINANCE:ETHUSDT'],
    isActive: false,
    symbol: 'ETHUSDT',
    category: 'Cryptocurrency',
    status: 'INACTIVE',
    tvLink: 'https://www.tradingview.com/chart?symbol=BINANCE:ETHUSDT',
    cgLink: 'https://www.coingecko.com/en/coins/ethereum',
    exchanges: ['BINANCE'],
    imageUrl: 'assets/icons/bitcoin.svg',
  },
  {
    id: 'alert3',
    action: 'BUY',
    alertName: 'Solana Price Alert',
    description: 'Solana price has surged.',
    creationTime: 1698547400,
    activationTime: 1698547500,
    activationTimeStr: '2023-10-29T12:10:00Z',
    price: 25,
    high: 30,
    low: 20,
    tvScreensUrls: ['https://www.tradingview.com/chart?symbol=BINANCE:SOLUSDT'],
    isActive: true,
    symbol: 'SOLUSDT',
    category: 'Cryptocurrency',
    status: 'ACTIVE',
    tvLink: 'https://www.tradingview.com/chart?symbol=BINANCE:SOLUSDT',
    cgLink: 'https://www.coingecko.com/en/coins/solana',
    exchanges: ['BINANCE'],
    imageUrl: 'assets/icons/bitcoin.svg',
  },
  {
    id: 'alert4',
    action: 'SELL',
    alertName: 'Cardano Price Alert',
    description: 'Cardano price is falling.',
    creationTime: 1698547600,
    activationTime: 1698547700,
    activationTimeStr: '2023-10-29T12:20:00Z',
    price: 0.5,
    high: 0.6,
    low: 0.4,
    tvScreensUrls: ['https://www.tradingview.com/chart?symbol=BINANCE:ADAUSDT'],
    isActive: true,
    symbol: 'ADAUSDT',
    category: 'Cryptocurrency',
    status: 'TRIGGERED',
    tvLink: 'https://www.tradingview.com/chart?symbol=BINANCE:ADAUSDT',
    cgLink: 'https://www.coingecko.com/en/coins/cardano',
    exchanges: ['BINANCE'],
    imageUrl: 'assets/icons/bitcoin.svg',
  },
  {
    id: 'alert5',
    action: 'BUY',
    alertName: 'Dogecoin Price Alert',
    description: 'Dogecoin price is rising.',
    creationTime: 1698547800,
    activationTime: 1698547900,
    activationTimeStr: '2023-10-29T12:30:00Z',
    price: 0.08,
    high: 0.1,
    low: 0.06,
    tvScreensUrls: [
      'https://www.tradingview.com/chart?symbol=BINANCE:DOGEUSDT',
    ],
    isActive: false,
    symbol: 'DOGEUSDT',
    category: 'Cryptocurrency',
    status: 'INACTIVE',
    tvLink: 'https://www.tradingview.com/chart?symbol=BINANCE:DOGEUSDT',
    cgLink: 'https://www.coingecko.com/en/coins/dogecoin',
    exchanges: ['BINANCE'],
    imageUrl: 'assets/icons/bitcoin.svg',
  },
  {
    id: 'alert6',
    action: 'SELL',
    alertName: 'Ripple Price Alert',
    description: 'Ripple price has dropped.',
    creationTime: 1698548000,
    activationTime: 1698548100,
    activationTimeStr: '2023-10-29T12:40:00Z',
    price: 0.5,
    high: 0.6,
    low: 0.4,
    tvScreensUrls: ['https://www.tradingview.com/chart?symbol=BINANCE:XRPUSDT'],
    isActive: true,
    symbol: 'XRPUSDT',
    category: 'Cryptocurrency',
    status: 'ACTIVE',
    tvLink: 'https://www.tradingview.com/chart?symbol=BINANCE:XRPUSDT',
    cgLink: 'https://www.coingecko.com/en/coins/xrp',
    exchanges: ['BINANCE'],
    imageUrl: 'assets/icons/bitcoin.svg',
  },
  {
    id: 'alert7',
    action: 'BUY',
    alertName: 'Polkadot Price Alert',
    description: 'Polkadot price is surging.',
    creationTime: 1698548200,
    activationTime: 1698548300,
    activationTimeStr: '2023-10-29T12:50:00Z',
    price: 7,
    high: 8,
    low: 6,
    tvScreensUrls: ['https://www.tradingview.com/chart?symbol=BINANCE:DOTUSDT'],
    isActive: true,
    symbol: 'DOTUSDT',
    category: 'Cryptocurrency',
    status: 'TRIGGERED',
    tvLink: 'https://www.tradingview.com/chart?symbol=BINANCE:DOTUSDT',
    cgLink: 'https://www.coingecko.com/en/coins/polkadot',
    exchanges: ['BINANCE'],
    imageUrl: 'assets/icons/bitcoin.svg',
  },
  {
    id: 'alert8',
    action: 'SELL',
    alertName: 'Chainlink Price Alert',
    description: 'Chainlink price is dropping.',
    creationTime: 1698548400,
    activationTime: 1698548500,
    activationTimeStr: '2023-10-29T13:00:00Z',
    price: 8,
    high: 9,
    low: 7,
    tvScreensUrls: [
      'https://www.tradingview.com/chart?symbol=BINANCE:LINKUSDT',
    ],
    isActive: false,
    symbol: 'LINKUSDT',
    category: 'Cryptocurrency',
    status: 'INACTIVE',
    tvLink: 'https://www.tradingview.com/chart?symbol=BINANCE:LINKUSDT',
    cgLink: 'https://www.coingecko.com/en/coins/chainlink',
    exchanges: ['BINANCE'],
    imageUrl: 'assets/icons/bitcoin.svg',
  },
  {
    id: 'alert9',
    action: 'BUY',
    alertName: 'Polygon Price Alert',
    description: 'Polygon price is increasing.',
    creationTime: 1698548600,
    activationTime: 1698548700,
    activationTimeStr: '2023-10-29T13:10:00Z',
    price: 1.2,
    high: 1.3,
    low: 1.1,
    tvScreensUrls: [
      'https://www.tradingview.com/chart?symbol=BINANCE:MATICUSDT',
    ],
    isActive: true,
    symbol: 'MATICUSDT',
    category: 'Cryptocurrency',
    status: 'ACTIVE',
    tvLink: 'https://www.tradingview.com/chart?symbol=BINANCE:MATICUSDT',
    cgLink: 'https://www.coingecko.com/en/coins/polygon',
    exchanges: ['BINANCE'],
    imageUrl: 'assets/icons/bitcoin.svg',
  },
  {
    id: 'alert10',
    action: 'SELL',
    alertName: 'Litecoin Price Alert',
    description: 'Litecoin price is declining.',
    creationTime: 1698548800,
    activationTime: 1698548900,
    activationTimeStr: '2023-10-29T13:20:00Z',
    price: 65,
    high: 70,
    low: 60,
    tvScreensUrls: ['https://www.tradingview.com/chart?symbol=BINANCE:LTCUSDT'],
    isActive: true,
    symbol: 'LTCUSDT',
    category: 'Cryptocurrency',
    status: 'TRIGGERED',
    tvLink: 'https://www.tradingview.com/chart?symbol=BINANCE:LTCUSDT',
    cgLink: 'https://www.coingecko.com/en/coins/litecoin',
    exchanges: ['BINANCE'],
    imageUrl: 'assets/icons/bitcoin.svg',
  },
];
